import type { Metadata } from "next";
import "./globals.css";
import { federo } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Multimedia Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${federo.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
